apiVersion: v1
kind: Service
metadata:
  name: "mylb1"
spec:
  type: LoadBalancer  # ✅ Explicitly define service type
  selector:
    app: web
  ports:
  - targetPort: 80  # ✅ Fixed spelling
    port: 8080
    nodePort: 30001
