apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myd1
spec:
  replicas: 3
  selector:
    matchLabels:   
      app: web  # ✅ matchLabels
    matchExpressions:
      - key: env
        operator: In
        values: ["prod", "test", "dev"]
      - key: team
        operator: In
        values: ["team1", "team2", "team3"]
      - key: region
        operator: In
        values: ["IN", "US", "UK"]
      - key: specific
        operator: In
        values: ["backend", "frontend", "database"]
  template:
    metadata:
      labels:
        app: web  # ✅ Must match matchLabels
        env: prod  # ✅ Must match matchExpressions conditions
        team: team3
        region: IN
        specific: backend
    spec: 
      containers:
      - name: myc1
        image: vimal13/apache-webserver-php
